trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/development.yml
      
    jobs:    
      - job: build_src
        steps:
          - template: steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'

      - job: test_src
        dependsOn: build_src
        steps:
          - template: steps/dotnet-test-steps.yml
            parameters:
              unitPath: '$(System.DefaultWorkingDirectory)/src'
              appcsKey: '$(appcsConnectionKey)'
              appcsConnection: '$(appcsConnection)'
              rgEnvironment: '$(rgEnvironment)'

      - job: deploy_nuget
        dependsOn: test_src
        steps:
          - template: steps/dotnet-pack-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'
              
          - template: steps/nuget-deploy-internal-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              nugetId: '$(nugetId)'

  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml    

    jobs:
      - job: build_src
        steps:
          - template: steps/dotnet-build-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'

      - job: test_src
        dependsOn: build_src
        steps:
          - template: steps/dotnet-test-steps.yml
            parameters:
              unitPath: '$(System.DefaultWorkingDirectory)/src'
              appcsKey: '$(appcsConnectionKey)'
              appcsConnection: '$(appcsConnection)'
              rgEnvironment: '$(rgEnvironment)'

      - job: deploy_nuget
        dependsOn: test_src
        steps:
          - template: steps/dotnet-pack-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              srcPath: '$(srcPath)'
              
          - template: steps/nuget-deploy-internal-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              nugetId: '$(nugetId)'