trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/lz-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'


  - stage: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/production.yml    

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/lz-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workName: '$(workName)'

      - job: deploy_appcs
        dependsOn: deploy_landing_zone
        steps:
          - template: steps/appcs-deploy-steps.yml
            parameters:
              armPath: 'infrastructure'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              appcsName: '$(appcsName)'
              appcsSku: '$(appcsSku)'