variables:
  - template: common.yml  
  - name: Environment
    value: 'Production'
  - name: rgName
    value: 'gtc-rg-shared-prod-001'
  - name: locationName
    value: 'West US 2'
  - name: 'appInsightsName'
    value: 'appi-shared-prod-001'
  - name: 'kvName'
    value: 'kv-shared-prod-001'    
  - name: 'nugetFeeds'
    value: 'config'
  - name: 'nugetId'
    value: '525a0dbd-3d6d-4f62-aba4-f4d004295d7d'
  - name: 'nugetType'
    value: 'external'
  - name: storageName
    value: 'stsharedprod001'
  - name: workspaceName
    value: 'work-shared-prod-001'
  - name: cognitiveServicesName
    value: 'cog-shared-prod-001'