variables:
  - group: gtc-rg-shared-prod
  - template: common.yml  
  - name: Environment
    value: 'Production'
  - name: rgName
    value: 'gtc-rg-shared-prod-225'
  - name: locationName
    value: 'West US 2'
  - name: 'appcsName'
    value: 'appcs-shared-prod-225'
  - name: 'appcsSku'
    value: 'Standard'
  - name: 'appInsightsName'
    value: 'appi-shared-prod-225'
  - name: 'kvName'
    value: 'kv-shared-prod-225'    
  - name: 'nugetServiceConnection'
    value: 'gtc-nuget-prod-001'
  - name: 'nugetFeeds'
    value: 'select'    
  - name: 'nugetType'
    value: 'external'
  - name: storageName
    value: 'stsharedprod225'
  - name: workspaceName
    value: 'work-shared-prod-225'